HW4_klin2_cdbruneau: Organism Class Reference
Organism Class Reference abstract
#include <Organism.h>
Public Member Functions
Organism ()
Organism (int r, int c)
Organism (bool b)
bool isPrey ()
virtual bool move (Grid *current)
virtual bool breed (Grid *current)=0
virtual bool eat (Grid *current)
virtual bool starve ()
void setAmAnt (bool b)
int getStepCount ()
void setStepCount (int s)
void setColumn (int c)
void setRow (int r)
int getRow ()
int getColumn ()
bool getProcessed ()
void setProcessed (bool setProcessed)
virtual ~Organism ()
Protected Attributes
int row = 0
int col = 0
int stepCount = 0
bool amAnt = false
bool processed = false
Constructor & Destructor Documentation
Organism() [1/3]
Organism::Organism ()
Function is the default constructor for an organism object that instantiates an Organism object.
Organism() [2/3]
Organism::Organism (int r, int c)
Function is another constructor for an organism object that instantiates an Organism object with r rows and c columns.
Parameters
r The row that the organism will be instantiated in.
c The column that the organism will be instantiated in.
References col, row, and stepCount.
Organism() [3/3]
Organism::Organism (bool b)
Function is another constructor for an organism object that instantiates an Organism object and sets the boolean value amAnt to the passes in param b.
Parameters
b A boolean value indicating whether an organism is an ant or not.
References amAnt.
~Organism()
Organism::~Organism () virtual
Function is a destructor that takes the Organism object and deletes it once the program is done using the object.
Member Function Documentation
breed()
virtual bool Organism::breed (Grid * current) pure virtual
Implemented in Doodlebug, and Ant.
Referenced by Production::playOne().
eat()
bool Organism::eat (Grid * current) virtual
Function tells whether an organism is a prey.
Returns
false This boolean value holds true for all organism unless ovverrided in child class.
Reimplemented in Doodlebug.
getColumn()
int Organism::getColumn ()
Function returns the current row of the organism.
Returns
row The current row that the organism is in.
References col.
getProcessed()
bool Organism::getProcessed ()
Function returns the processed status of the organism.
Returns
row The current processed status of the organism.
References processed.
Referenced by Production::playOne().
getRow()
int Organism::getRow ()
Function returns the current row of the organism.
Returns
row The current row that the organism is in.
References row.
getStepCount()
int Organism::getStepCount ()
Function returns the current stepCount of the organism.
Returns
stepCount A number of steps that the organism has survived for.
References stepCount.
Referenced by Production::playOne().
isPrey()
bool Organism::isPrey ()
Function tells whether an organism is a prey.
Returns
status A boolean value that indicates true if an organism is prey and false if the organism is not prey.
References amAnt.
Referenced by Grid::createOrganism().
move()
bool Organism::move (Grid * current) virtual
Functions tells whether if the organism can move or not, and then moves it accordingly.
Parameters
current A pointer to the current board that the game is being played on.
Returns
status A boolean value that indicates true if an ant can move and false if the ant cannot move.
Reimplemented in Doodlebug.
References col, Grid::findMove(), Grid::moveOrganism(), and row.
Referenced by Tests2::antsMoveTest(), Doodlebug::move(), and Production::playOne().
setAmAnt()
void Organism::setAmAnt (bool b)
Function sets the organism as an ant.
References amAnt.
setColumn()
void Organism::setColumn (int c)
Function sets the current row of the organism.
Parameters
r The given row that the organism will be in.
References col.
Referenced by Grid::moveOrganism().
setProcessed()
void Organism::setProcessed (bool setProcessed)
Function sets the current processed status of the organism.
Parameters
setProcessed A boolean value indicating what the processed status should be set to.
References processed.
Referenced by Production::playOne().
setRow()
void Organism::setRow (int r)
Function sets the current row of the organism.
Parameters
r The given row that the organism will be in.
References row.
Referenced by Grid::moveOrganism().
setStepCount()
void Organism::setStepCount (int s)
Function sets the current stepCount of the organism.
Parameters
s The given number of steps that the organism has survived for.
References stepCount.
Referenced by Tests2::antsBreedTest(), Tests2::doodleBreedTest(), and Production::playOne().
starve()
bool Organism::starve () virtual
Returns whether or not the organism has starved.
Returns
false This boolean value holds true for all organisms, unless overrided in child class.
Reimplemented in Doodlebug.
Referenced by Production::playOne().
Field Documentation
amAnt
bool Organism::amAnt = false protected
Referenced by isPrey(), Organism(), and setAmAnt().
col
int Organism::col = 0 protected
Referenced by Ant::Ant(), Ant::breed(), Doodlebug::breed(), Doodlebug::Doodlebug(), Doodlebug::eat(), getColumn(), move(), Organism(), and setColumn().
processed
bool Organism::processed = false protected
Referenced by getProcessed(), and setProcessed().
row
int Organism::row = 0 protected
Referenced by Ant::Ant(), Ant::breed(), Doodlebug::breed(), Doodlebug::Doodlebug(), Doodlebug::eat(), getRow(), move(), Organism(), and setRow().
stepCount
int Organism::stepCount = 0 protected
Referenced by Ant::breed(), Doodlebug::breed(), getStepCount(), Organism(), and setStepCount().
The documentation for this class was generated from the following files:
Organism.h
Organism.cpp