HW4_klin2_cdbruneau: Grid Class Reference
Grid Class Reference
#include <Grid.h>
Public Member Functions
Grid ()
Grid (int nSquaresOnASide)
bool setCellOccupant (int r, int c, occupationStatus g)
occupationStatus getCellOccupant (int r, int c)
occupationStatus * checkNeighbors (int r, int c)
bool * findFood (int r, int c)
bool * findMove (int r, int c)
void moveOrganism (int r_old, int c_old, int r_new, int c_new)
void setCellOrganism (int r, int c, Organism *g)
Organism * getCellOrganism (int r, int c)
Cell getCell (int r, int c)
void printGrid ()
void deleteOrganism (int r, int c)
bool createOrganism (int r, int c, Organism *mother)
virtual ~Grid ()
Private Attributes
int n =0
Cell ** myGridCells_ptr_array = (Cell**)nullptr
Constructor & Destructor Documentation
Grid() [1/2]
Grid::Grid ()
Function is the default constructor for a Grid object that instantiates a Grid object with the default grid value set to 10..
Grid() [2/2]
Grid::Grid (int nSquaresOnASide)
Function is another constructor for a Grid object that instantiates a grid object and sets the size of the grid, n, to the given parameter nSquaresOnSide, and allocates a array of pointers with n amount of row pointers and allocates memory for n amount of columns in each row.
Parameters
nSquaresOnASide The number of rows and columns on each side of the newly created grid.
References myGridCells_ptr_array, and n.
~Grid()
Grid::~Grid () virtual
Function is a destructor that takes the Grid object and deletes it once the program is done using the object.
References myGridCells_ptr_array, n, and Cell::~Cell().
Referenced by Tests2::gridTest().
Member Function Documentation
checkNeighbors()
occupationStatus * Grid::checkNeighbors (int r, int c)
Returns a pointer to an array of occupation statuses that represents the occupied status for the positions North , South, East, West specifically in that order.
Parameters
r The row of the cell whose neighbors we check.
c The column of the cell whose neighbors we check.
Returns
values An array of boolean values that determines if the cells north, south, east, and west are occupied.
References getCellOccupant().
Referenced by Tests2::checkNeighborsTest(), findFood(), and findMove().
createOrganism()
bool Grid::createOrganism (int r, int c, Organism * mother)
Function creates a new organism, an ant or a doodlebug depending on the type of the mother organism, in the place of the given row and column.
Parameters
r The row of the cell whose organism is to be deleted.
c The column of the cell whose organism is to be deleted.
mother The organism of the original cell that the new cell will take after of.
References ant, doodlebug, getCellOccupant(), Organism::isPrey(), myGridCells_ptr_array, Cell::setCurrentOrganism(), Cell::setOccupant(), and unavailable.
Referenced by Ant::breed(), and Doodlebug::breed().
deleteOrganism()
void Grid::deleteOrganism (int r, int c)
Function deletes the organism in the location of the passed in parameters, r, and c.
Parameters
r The row of the cell whose organism is to be deleted.
c The column of the cell whose organism is to be deleted.
References empty, getCellOccupant(), Cell::getCurrentOrganism(), myGridCells_ptr_array, Cell::setCurrentOrganism(), Cell::setOccupant(), and unavailable.
Referenced by Tests2::cellOccupantOrganismTests(), Doodlebug::eat(), and Production::playOne().
findFood()
bool * Grid::findFood (int r, int c)
Returns a pointer to an array of boolean values that indicates whether or not the cell occupant is and ant(food).
Parameters
r The row of the cell whose neighbors we check if they are ants(food).
c The column of the cell whose neighbors we check if they are ants(food).
Returns
isAnt A array of boolean values indicating if the neighbors is food. true i s food, and false is not food.
References ant, and checkNeighbors().
Referenced by Doodlebug::eat(), and Tests2::findFoodTest().
findMove()
bool * Grid::findMove (int r, int c)
Returns a pointer to an array of boolean values that indicates whether or not the cell occupant is empty.
Parameters
r The row of the cell whose neighbors we check if they are empty.
c The column of the cell whose neighbors we check if they are empty.
Returns
isEmpty A array of boolean values indicating if the neighbors is empty. true is empty, and false is not empty.
References checkNeighbors(), and empty.
Referenced by Ant::breed(), Doodlebug::breed(), Tests2::findMoveTest(), and Organism::move().
getCell()
Cell Grid::getCell (int r, int c)
References myGridCells_ptr_array.
Referenced by Tests2::printGridAndCellTest().
getCellOccupant()
occupationStatus Grid::getCellOccupant (int r, int c)
Function retrieves the occupant status in the given location of the passed in row and column.
Parameters
r The row that the occupant status must be retrieved.
c The column that the occupant status must be retrieved.
Returns
myGridCells_ptr_array[r][c].getOccupant() An enum that indicates the current occupation status of the cell. If cell is off the edge of the grid, returns unavailable.
References Cell::getOccupant(), myGridCells_ptr_array, n, and unavailable.
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Tests2::cellOccupantOrganismTests(), checkNeighbors(), createOrganism(), deleteOrganism(), Tests2::doodleBreedTest(), Tests2::doodleEatTest(), Tests2::doodleMoveTest(), Tests2::gridTest(), Tests2::makeAntsTest(), moveOrganism(), Tests2::moveOrganismTest(), Production::playOne(), Production::Production(), and Production::runProduction().
getCellOrganism()
Organism * Grid::getCellOrganism (int r, int c)
Function retrieves the current organism in the given location of the passed in row and column.
Parameters
r The row that the occupant organism must be retrieved.
c The column that the occupant organism must be retrieved.
Returns
myGridCells_ptr_array[r][c].getCurrentOrganism() A Organism pointer value that indicates the current organism in the cell.
References Cell::getCurrentOrganism(), and myGridCells_ptr_array.
Referenced by Tests2::cellOccupantOrganismTests(), and Production::playOne().
moveOrganism()
void Grid::moveOrganism (int r_old, int c_old, int r_new, int c_new)
Functions moves the organism from one cell to another cell.
Parameters
r_old The current row of the cell that will be moved.
c_old The current column of the cell that will be moved.
r_new The new row of the cell that will move to.
c_new The new column of the cell that will move to.
References empty, getCellOccupant(), Cell::getCurrentOrganism(), myGridCells_ptr_array, setCellOccupant(), Organism::setColumn(), Cell::setCurrentOrganism(), and Organism::setRow().
Referenced by Doodlebug::eat(), Organism::move(), and Tests2::moveOrganismTest().
printGrid()
void Grid::printGrid ()
Prints out the grid for one play.
References myGridCells_ptr_array, n, and Cell::printCell().
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Tests2::cellOccupantOrganismTests(), Tests2::checkNeighborsTest(), Tests2::doodleBreedTest(), Tests2::doodleEatTest(), Tests2::findFoodTest(), Tests2::findMoveTest(), Tests2::makeAntsTest(), Tests2::moveOrganismTest(), Tests2::printGridAndCellTest(), Production::Production(), and Production::runProduction().
setCellOccupant()
bool Grid::setCellOccupant (int r, int c, occupationStatus g)
Function sets the occupant status in the given location of the passed in row and column.
Parameters
r The row that the occupant status must be changed.
c The column that the occupant status must be changed.
g The occupant status that the cell would be set to.
Returns
myGridCells_ptr_array[r][c].setOccupant(g) A boolean value that returns true if you were able to set the occupant and false if you were unable to set the occupant.
References myGridCells_ptr_array, and Cell::setOccupant().
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Tests2::cellOccupantOrganismTests(), Tests2::checkNeighborsTest(), Tests2::doodleBreedTest(), Tests2::doodleEatTest(), Tests2::doodleMoveTest(), Tests2::findFoodTest(), Tests2::findMoveTest(), Tests2::gridTest(), Tests2::makeAntsTest(), moveOrganism(), Tests2::moveOrganismTest(), Tests2::printGridAndCellTest(), and Production::Production().
setCellOrganism()
void Grid::setCellOrganism (int r, int c, Organism * g)
Function sets the current organism in the given location of the passed in row and column.
Parameters
r The row that the organism must be changed.
c The column that the organism must be changed.
g The pointer to the organism that needs to be set.
Returns
myGridCells_ptr_array[r][c].setOccupant(g) A boolean value that returns true if you were able to set the occupant and false if you were unable to set the occupant.
References myGridCells_ptr_array, and Cell::setCurrentOrganism().
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Tests2::cellOccupantOrganismTests(), Tests2::checkNeighborsTest(), Tests2::doodleBreedTest(), Tests2::doodleEatTest(), Tests2::doodleMoveTest(), Tests2::findFoodTest(), Tests2::findMoveTest(), Tests2::moveOrganismTest(), Tests2::printGridAndCellTest(), and Production::Production().
Field Documentation
myGridCells_ptr_array
Cell** Grid::myGridCells_ptr_array = (Cell**)nullptr private
Referenced by createOrganism(), deleteOrganism(), getCell(), getCellOccupant(), getCellOrganism(), Grid(), moveOrganism(), printGrid(), setCellOccupant(), setCellOrganism(), and ~Grid().
n
int Grid::n =0 private
Referenced by getCellOccupant(), Grid(), printGrid(), and ~Grid().
The documentation for this class was generated from the following files:
Grid.h
Grid.cpp