HW4_klin2_cdbruneau: Cell Class Reference
Cell Class Reference
#include <Cell.h>
Public Member Functions
Cell ()
bool setOccupant (occupationStatus g)
occupationStatus getOccupant ()
void printCell ()
Organism * getCurrentOrganism ()
Organism * setCurrentOrganism (Organism *newOccupant)
virtual ~Cell ()
Private Attributes
Organism * occupant
occupationStatus guest = empty
Constructor & Destructor Documentation
Cell()
Cell::Cell ()
Function is the default constructor for a Cell object that instantiates a Cell object with an empty guest.
References empty, guest, and occupant.
~Cell()
Cell::~Cell () virtual
Function is a destructor that takes the Cell object and deletes it once the program is done using the object.
Referenced by Grid::~Grid().
Member Function Documentation
getCurrentOrganism()
Organism * Cell::getCurrentOrganism ()
Function that returns the Cell's occupant.
Returns
occupant The current occupant of a cell.
References occupant.
Referenced by Grid::deleteOrganism(), Grid::getCellOrganism(), and Grid::moveOrganism().
getOccupant()
occupationStatus Cell::getOccupant ()
Function that returns the Cell's occupancy status.
Returns
guest A value that indicates the occupancy status of a cell.
References guest.
Referenced by Grid::getCellOccupant().
printCell()
void Cell::printCell ()
Function that prints a character representing the current occupation status of the cell. If the occupation status is ant, this function prints 'o' If the occupation status is a doodlebug, this function prints 'x' If the occupation status is empty, this function prints ' '
References ant, doodlebug, empty, and guest.
Referenced by Grid::printGrid(), and Tests2::printGridAndCellTest().
setCurrentOrganism()
Organism * Cell::setCurrentOrganism (Organism * newOccupant)
Function that sets the Cell's occupant.
Parameters
newOccupant A pointer to an organism object that the cell's organism will be set to.
Returns
occupant The new occupant of a cell.
References occupant.
Referenced by Grid::createOrganism(), Grid::deleteOrganism(), Grid::moveOrganism(), and Grid::setCellOrganism().
setOccupant()
bool Cell::setOccupant (occupationStatus g)
Function is a constructor for a cell object that instantiates a cell object and sets the occupancy status to the passed in parameter, g, and returns the result.
Returns
result A boolean value that indicates true if the occupant status has been set and false if the status has not been set because the Cell was occupied.
References empty, and guest.
Referenced by Grid::createOrganism(), Grid::deleteOrganism(), and Grid::setCellOccupant().
Field Documentation
guest
occupationStatus Cell::guest = empty private
Referenced by Cell(), getOccupant(), printCell(), and setOccupant().
occupant
Organism* Cell::occupant private
Referenced by Cell(), getCurrentOrganism(), and setCurrentOrganism().
The documentation for this class was generated from the following files:
Cell.h
Cell.cpp