HW4_klin2_cdbruneau: Tests2 Class Reference
Tests2 Class Reference
#include <Tests2.h>
Public Member Functions
Tests2 ()
bool doTests ()
bool gridTest ()
bool makeAntsTest ()
bool antsMoveTest ()
bool antsBreedTest ()
bool antsDieTest ()
bool makeDoodlesTest ()
bool doodleMoveTest ()
bool doodleBreedTest ()
bool doodleEatTest ()
bool doodleDietest ()
bool cellOccupantOrganismTests ()
bool checkNeighborsTest ()
bool findFoodTest ()
bool findMoveTest ()
bool moveOrganismTest ()
bool printGridAndCellTest ()
virtual ~Tests2 ()
Constructor & Destructor Documentation
Tests2()
Tests2::Tests2 ()
Function is the default constructor for a test object that instantiates an test object.
~Tests2()
Tests2::~Tests2 () virtual
Function is a destructor that takes the Test object and deletes it once the program is done using the object.
Referenced by main().
Member Function Documentation
antsBreedTest()
bool Tests2::antsBreedTest ()
Function calls the antsBreedTest and returns true if tests pass.
Returns
result true if the tests were puts("Printing grid after."); myGrid_p->printGrid();able to pass and false if they were not able to pass.
References ant, Ant::breed(), empty, Grid::getCellOccupant(), Grid::printGrid(), Grid::setCellOccupant(), Grid::setCellOrganism(), and Organism::setStepCount().
Referenced by doTests().
antsDieTest()
bool Tests2::antsDieTest ()
Function calls the antsDieTest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
References ant, doodlebug, Doodlebug::eat(), Grid::getCellOccupant(), Grid::printGrid(), Grid::setCellOccupant(), and Grid::setCellOrganism().
Referenced by doTests().
antsMoveTest()
bool Tests2::antsMoveTest ()
Function calls the antsMovetest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
References ant, empty, Grid::getCellOccupant(), Organism::move(), Grid::printGrid(), Grid::setCellOccupant(), and Grid::setCellOrganism().
Referenced by doTests().
cellOccupantOrganismTests()
bool Tests2::cellOccupantOrganismTests ()
References ant, Grid::deleteOrganism(), doodlebug, empty, Grid::getCellOccupant(), Grid::getCellOrganism(), Grid::printGrid(), Grid::setCellOccupant(), and Grid::setCellOrganism().
Referenced by doTests().
checkNeighborsTest()
bool Tests2::checkNeighborsTest ()
Function calls the checkNeighborsTest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
References ant, Grid::checkNeighbors(), empty, Grid::printGrid(), Grid::setCellOccupant(), Grid::setCellOrganism(), and unavailable.
Referenced by doTests().
doodleBreedTest()
bool Tests2::doodleBreedTest ()
Function calls the doodleBreedTest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
References Doodlebug::breed(), doodlebug, empty, Grid::getCellOccupant(), Grid::printGrid(), Grid::setCellOccupant(), Grid::setCellOrganism(), and Organism::setStepCount().
Referenced by doTests().
doodleDietest()
bool Tests2::doodleDietest ()
Function calls the doodleDietest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
Referenced by doTests().
doodleEatTest()
bool Tests2::doodleEatTest ()
Function calls the doodleEatTest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
References ant, doodlebug, Doodlebug::eat(), Grid::getCellOccupant(), Grid::printGrid(), Grid::setCellOccupant(), and Grid::setCellOrganism().
Referenced by doTests().
doodleMoveTest()
bool Tests2::doodleMoveTest ()
Function calls the doodleMoveTest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
References doodlebug, Grid::getCellOccupant(), Doodlebug::move(), Grid::setCellOccupant(), and Grid::setCellOrganism().
Referenced by doTests().
doTests()
bool Tests2::doTests ()
Function calls all of the test functions and returns a boolean value that indicates whether or not all the tests passed or not.
Returns
results A boolean value that reads true if all of the tests passed and false if any of the tests fail.
References antsBreedTest(), antsDieTest(), antsMoveTest(), cellOccupantOrganismTests(), checkNeighborsTest(), doodleBreedTest(), doodleDietest(), doodleEatTest(), doodleMoveTest(), findFoodTest(), findMoveTest(), gridTest(), makeAntsTest(), makeDoodlesTest(), moveOrganismTest(), and printGridAndCellTest().
Referenced by main().
findFoodTest()
bool Tests2::findFoodTest ()
Function calls the findFoodTest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
References ant, doodlebug, Grid::findFood(), Grid::printGrid(), Grid::setCellOccupant(), and Grid::setCellOrganism().
Referenced by doTests().
findMoveTest()
bool Tests2::findMoveTest ()
Function calls the findMoveTest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
References ant, doodlebug, Grid::findMove(), Grid::printGrid(), Grid::setCellOccupant(), and Grid::setCellOrganism().
Referenced by doTests().
gridTest()
bool Tests2::gridTest ()
Function calls the grid object and checks whether the grid was instantiated correctly and if the grid sets the occupancy statuses correctly.
Returns
results A boolean value that reads true if the the grid was able to set the cell occupancy statuses correctly.
References ant, empty, Grid::getCellOccupant(), Grid::setCellOccupant(), and Grid::~Grid().
Referenced by doTests().
makeAntsTest()
bool Tests2::makeAntsTest ()
Function checks if the ant object were able to be instantiate correctly and if the occupancy status was set correctly.
Returns
result A boolean value that is true if the ant object was instantiated correctly and if its occupancy status was set to ant, and false if this was not done.
References ant, doodlebug, empty, Grid::getCellOccupant(), Grid::printGrid(), and Grid::setCellOccupant().
Referenced by doTests().
makeDoodlesTest()
bool Tests2::makeDoodlesTest ()
Function calls the makeDoodlesTest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
Referenced by doTests().
moveOrganismTest()
bool Tests2::moveOrganismTest ()
Function calls the moveOrganismTest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
References ant, doodlebug, empty, Grid::getCellOccupant(), Grid::moveOrganism(), Grid::printGrid(), Grid::setCellOccupant(), and Grid::setCellOrganism().
Referenced by doTests().
printGridAndCellTest()
bool Tests2::printGridAndCellTest ()
Function calls the printGridTest and the printCellTest and returns true if tests pass.
Returns
result true if the tests were able to pass and false if they were not able to pass.
References ant, doodlebug, Grid::getCell(), Cell::printCell(), Grid::printGrid(), Grid::setCellOccupant(), and Grid::setCellOrganism().
Referenced by doTests().
The documentation for this class was generated from the following files:
Tests2.h
Tests2.cpp