HW4_klin2_cdbruneau: Production Class Reference
Production Class Reference
#include <Production.h>
Public Member Functions
Production (int argc, char *argv[])
bool runProduction ()
virtual ~Production ()
void playOne ()
Private Attributes
int timestepsLeft =1000
int timesRun = 0
int gridSize = 20
int doodlebugs = 5
int ants = 100
int seed = 1
int pause = 0
Grid * board
int newAnts = 0
int newDoodlebugs = 0
int remainingAnts = 0
int remainingDoodlebugs = 0
Constructor & Destructor Documentation
Production()
Production::Production (int argc, char * argv[])
Function is the default constructor for a production object that instantiates Production object, and sets the timestepsleft to 100.
Parameters
argc Number of words on the command line
argv Array of pointers to character strings representing the words on the command line.
References ant, ants, board, doodlebug, doodlebugs, empty, Grid::getCellOccupant(), gridSize, pause, Grid::printGrid(), seed, Grid::setCellOccupant(), Grid::setCellOrganism(), and timestepsLeft.
Referenced by main().
~Production()
Production::~Production () virtual
Function is a destructor that takes the production object and deletes it once the program is done using the object.
Referenced by main().
Member Function Documentation
playOne()
void Production::playOne ()
Runs through one iteration of the game.
References ant, board, Organism::breed(), Grid::deleteOrganism(), doodlebug, Grid::getCellOccupant(), Grid::getCellOrganism(), Organism::getProcessed(), Organism::getStepCount(), gridSize, Organism::move(), newAnts, newDoodlebugs, Organism::setProcessed(), Organism::setStepCount(), Organism::starve(), and timesRun.
Referenced by runProduction().
runProduction()
bool Production::runProduction ()
Function that runs the production while there are still time steps left.
Returns
result A boolean value true if the production was able to run successfully, and false if the production was not able to run successfully.
References ant, ants, board, doodlebug, doodlebugs, Grid::getCellOccupant(), gridSize, newAnts, newDoodlebugs, pause, playOne(), Grid::printGrid(), remainingAnts, remainingDoodlebugs, seed, timesRun, and timestepsLeft.
Referenced by main().
Field Documentation
ants
int Production::ants = 100 private
Referenced by Production(), and runProduction().
board
Grid* Production::board private
Referenced by playOne(), Production(), and runProduction().
doodlebugs
int Production::doodlebugs = 5 private
Referenced by Production(), and runProduction().
gridSize
int Production::gridSize = 20 private
Referenced by playOne(), Production(), and runProduction().
newAnts
int Production::newAnts = 0 private
Referenced by playOne(), and runProduction().
newDoodlebugs
int Production::newDoodlebugs = 0 private
Referenced by playOne(), and runProduction().
pause
int Production::pause = 0 private
Referenced by Production(), and runProduction().
remainingAnts
int Production::remainingAnts = 0 private
Referenced by runProduction().
remainingDoodlebugs
int Production::remainingDoodlebugs = 0 private
Referenced by runProduction().
seed
int Production::seed = 1 private
Referenced by Production(), and runProduction().
timesRun
int Production::timesRun = 0 private
Referenced by playOne(), and runProduction().
timestepsLeft
int Production::timestepsLeft =1000 private
Referenced by Production(), and runProduction().
The documentation for this class was generated from the following files:
Production.h
Production.cpp